site_name: NoordveldRP Wetboek
theme:
  name: material
  features:
    - navigation.sections
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: blue

markdown_extensions:
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/5CnzPFU42z

copyright: |
  &copy; 2024 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">Noordveld Roleplay</a>
